### ISSUE TITLE
Add support for recursive files and listing from STDIN

### ISSUE THREAD

**Issue by commial** [ANSSI-FR/MLA#15]
In `mlar create`:
* If a directory is given as input, recursively add its files in the archive
* If `-` is given as a filename, add every files from STDIN (a path per line)

**Comment by omac777** [comment]
Thank you for the prompt replies.  APPENDING is not required, but rather to work around the undesireable CLI command-line length constraint which limits the number of files added to the archive on the CLI command-line.

In the same manner, how about adding switches to the "mlar create".  As a result, mlar would hold a vector of files_to_add and an array of directories_to_add.  Optionally use the standard input as the argument to each of these switches, but only once one the CLI command-line of course otherwise you will have redundant file listings as input.

- "--input-directory-list"

- "--input-file-list"

i.e.
```
mlar create -p key.pub -o my_archive.mla --input-directory-list inputdirlist.txt --input-directory-list inputdirlist2.txt --input-directory-list inputdirlist3.txt --input-file-list inputfilelist.txt --input-file-list inputfilelist2.txt --input-file-list inputfilelist3.txt
find blah/ -type d -print |mlar create -p key.pub -o my_archive.mla --input-directory-list -
find blah/ -type f -print |mlar create -p key.pub -o my_archive.mla --input-file-list  -
```

**Comment by commial** [comment]
From what I understand, having the behavior described in the issue would work for this case, by either:

* `mlar create -p key.pub -o my_archive.mla dir1 dir2 dir3 file1 file2 ...`
* `cat filelist1.txt filelist2.txt filelist3.txt filedir1.txt ... | mlar create -p key.pub -o my_archive.mla -`

That way, the code of `mlar create` would stay, hopefully, not too complex.

**Comment by omac777** [comment]
I can understand the code may not be permitted to be complex, but you may introduce sophistication by separating the different capabilities in different functions which would be deemed with acceptable complexity levels.

The clap crate has a multiple property for a particular switch that collects all those values passed in as input-dir-list and input-fle-list will end up in their respective vectors/arrays.
```
 Arg::new("package")
                        .about("packages")
                        .multiple(true)
                        .required_unless_one(&["search"])
                        .takes_value(true),
```

Let me re-emphasize the necessity for input-file-list and input-directory-list switches since you mentioned:
```
mlar create -p key.pub -o my_archive.mla dir1 dir2 dir3 file1 file2 ...
```
For use case scenarios where you have a smaller set of input directories and a smaller set of input files, the CLI will perform as expected.
BUT where the number for dirs reaches an enormous directory count on the command line itself, the command will break.
Where the number of files reaches an enormous file count on the command line itself, the command will break.  Even worse the command might not perform as expected with all the entire set specified.  Depending on the operating system, the os might simply cut the cli string to the max and continue to execute the command with a smaller subset of the dirs/files which is a worst case scenario.  mlar might actually state it succeeded in creating the archive, but it is incomplete.

You want to build a tool everyone can count on and provide guarantees.  That's why you're building it with rust and really appreciate that.   That said you need to ensure edge use cases where breakages might occur are not allowed.  I would recommend not accepting an unlimited number of files/directories at the CLI.  I would recommend you document for millions of files, you provide them within an input-file-list file.  I would recommend you document for millions of different directories, you provide them within an input-directory-list file.  That ensures the simplicity of the command-line by keeping it short, hopefully less than 1 KiloByte of characters string length which the operating system command line can easily handle while providing enormous capability of handling any count of directories or files within the .mla archive.

Thank you for listening.

**Comment by commial** [comment]
I apologize if I was not clear. I do agree with you on the command line length limitation, that's one of the reason of this issue.

My point is more about the necessity of the switches (one for directories, one for files), given the presence of a way to specify them through STDIN (that was the second example with `cat ... | mlar create ... -`).
It seems to me that it fits your needs, while allowing common UNIX-style composing. It could be even better if STDIN is stream read, allowing to start building the archive (CPU-bound) while a command (IO-bound) is running (as in `find / -print | mlar create ...`).

One argument I could see for a file listing switch is the ease of use on others OS. But again, I don't see the point of making separate switch for directories and files.

Am I missing something?

**Comment by catwell** [comment]
Maybe slightly unrelated to this, but if you support STDIN, you may want the ability to stream the data itself like age does, to leverage the streaming capability.

One use case (where I currently use age) is DB backups: `pg_dump /... | mlar create ...`.

**Comment by commial** [comment]
It's an interesting use case.
The thing is that MLA is an *archive* file format, like `tar`, whereas `age` is made to get a stream, much more like `gzip`.

If I keep `tar` as an example, there is no way (to my knowlegde) to directly add a file in the archive from STDIN. And, indeed, it would mean giving an arbitrary name to the file.
But with `tar -T -`, and regarding this current conversation this is probably a good idea, one can provides the file list from STDIN.

For your needs, a namedpipe could be a solution, as in `zip --fifo output.zip /path/to/pipe`.

**Comment by catwell** [comment]
You are right, technically it is possible to specify the filename from the CLI but the only popular tool I found which does that is [7zip](https://sevenzip.osdn.jp/chm/cmdline/switches/stdin.htm).

**Comment by omac777** [comment]
> I apologize if I was not clear. I do agree with you on the command line length limitation, that's one of the reason of this issue.
> 
> My point is more about the necessity of the switches (one for directories, one for files), given the presence of a way to specify them through STDIN (that was the second example with `cat ... | mlar create ... -`).
> It seems to me that it fits your needs, while allowing common UNIX-style composing. It could be even better if STDIN is stream read, allowing to start building the archive (CPU-bound) while a command (IO-bound) is running (as in `find / -print | mlar create ...`).
> 
> One argument I could see for a file listing switch is the ease of use on others OS. But again, I don't see the point of making separate switch for directories and files.
> 
> Am I missing something?

Locally, you're right. The --input-directory-listing is not necessary since directories are automatically created within the --input-file-list when examining the file's relative path sub parts.  It is desirable to have the ability for multiple input file lists however for which standard input is insufficient.  Here is one such scenario:

1. create an input file list from 3 different directories

```
find /home/loongson/MLA/target/release/deps/ -type f -print > localhostfilelist.txt
find /home/loongson/MLA/target/release/build/ -type f -print >> localhostfilelist.txt
find /home/loongson/MLA/target/release/examples/ -type f -print >> localhostfilelist.txt
```

2. create an .mla file based on the above input file list. Extending this further, within the "--files-from=" argument itself, you may allow for rsync-like urls:
```
mlar create -p key.pub -o user4@host4:/path/to/archive.mla --files-from=localhostfilelist.txt --files-from=user2@host2:/path/to/filelist2.txt --files-from=user3@host3:/path/to/filelist3.txt
 ```

I know this would be a bit more sophisticated than intended, but it could be as versatile yet more performant than rsync.
Your data structure and security measures to preserve the integrity of the .mla are still intact with this capability.

I apologize for bringing this on a tangent with the rsync-like capability.

Thank you again for listening.

**Comment by commial** [comment]
As the issue where closely related with #64, I'm closing it too.

It seems to fulfill the basic need (without the consideration for rsync like URI or file listing).

If it is an actual need or that one encounters use cases that cannot resolved in a satisfying manner, I would be pleased to discuss it in a dedicated issue.
