### ISSUE TITLE
Are MLA archives reproducible ?

### ISSUE THREAD

**Issue by maaaaz** [ANSSI-FR/MLA#229]
Hello there,

Thanks for this project.

Are MLA archives reproducible ?
I haven't tested but if I create 2 times an archive from the same input files, will the archive be exactly the same (hence having the same SHA-512 hash for instance) ? 

Because zip ones are not reproducible: 
https://github.com/drivendataorg/repro-zipfile?tab=readme-ov-file#how-does-repro-zipfile-work

Cheers!

**Comment by extiop** [comment]
Hello,

Thanks for your interest in MLA.

Unencrypted MLA archives are reproductible as we don't use metadata such as files timestamp creation or modification like ZIP ones. Obviously, encrypted ones, with a generated symetric key for data encryption for each one are not.

I hope I've answered your question, do not hesitate to reopen the issue otherwise.

**Comment by maaaaz** [comment]
Yes, thank you !
